export const COREVO_ABI = [
  { inputs: [], name: "AlreadyCommitted", type: "error" },
  { inputs: [], name: "AlreadyFinished", type: "error" },
  { inputs: [], name: "AlreadyRevealed", type: "error" },
  { inputs: [], name: "ArrayLengthMismatch", type: "error" },
  { inputs: [], name: "CommitPhaseEnded", type: "error" },
  { inputs: [], name: "InvalidDuration", type: "error" },
  { inputs: [], name: "NoVoters", type: "error" },
  { inputs: [], name: "NotAVoter", type: "error" },
  { inputs: [], name: "NotCommitted", type: "error" },
  { inputs: [], name: "NotInCommitPhase", type: "error" },
  { inputs: [], name: "NotInRevealPhase", type: "error" },
  { inputs: [], name: "RevealPhaseEnded", type: "error" },
  { inputs: [], name: "RevealPhaseNotEnded", type: "error" },
  { inputs: [], name: "ZeroPubKey", type: "error" },
  { inputs: [], name: "ZeroSalt", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "pubKey", type: "bytes32" },
    ],
    name: "KeyAnnounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: true, name: "proposer", type: "address" },
      { indexed: false, name: "contextHash", type: "bytes32" },
      { indexed: false, name: "isPublic", type: "bool" },
      { indexed: false, name: "commitDeadline", type: "uint64" },
      { indexed: false, name: "revealDeadline", type: "uint64" },
    ],
    name: "ProposalCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, name: "proposalId", type: "uint256" }],
    name: "ProposalFinished",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: true, name: "voter", type: "address" },
      { indexed: false, name: "oneTimeSalt", type: "bytes32" },
    ],
    name: "SaltRevealed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: true, name: "voter", type: "address" },
      { indexed: false, name: "commitment", type: "bytes32" },
    ],
    name: "VoteCommitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "proposalId", type: "uint256" },
      { indexed: true, name: "voter", type: "address" },
      { indexed: false, name: "encryptedSalt", type: "bytes" },
    ],
    name: "VoterInvited",
    type: "event",
  },
  {
    inputs: [{ name: "pubKey", type: "bytes32" }],
    name: "announceKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "proposalId", type: "uint256" },
      { name: "commitment", type: "bytes32" },
    ],
    name: "commitVote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    name: "commitments",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "vote", type: "uint8" },
      { name: "oneTimeSalt", type: "bytes32" },
      { name: "commonSalt", type: "bytes32" },
    ],
    name: "computeCommitment",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { name: "contextHash", type: "bytes32" },
      { name: "voters", type: "address[]" },
      { name: "encryptedSalts", type: "bytes[]" },
      { name: "isPublic", type: "bool" },
      { name: "commitDuration", type: "uint64" },
      { name: "revealDuration", type: "uint64" },
    ],
    name: "createProposal",
    outputs: [{ name: "proposalId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "encryptionKeys",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "finalizeProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "getRevealProgress",
    outputs: [
      { name: "committed", type: "uint32" },
      { name: "revealed", type: "uint32" },
      { name: "unrevealed", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "getVoters",
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "proposalId", type: "uint256" }],
    name: "isRevealOpen",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    name: "isVoter",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { name: "proposer", type: "address" },
      { name: "contextHash", type: "bytes32" },
      { name: "phase", type: "uint8" },
      { name: "isPublic", type: "bool" },
      { name: "commitDeadline", type: "uint64" },
      { name: "revealDeadline", type: "uint64" },
      { name: "voterCount", type: "uint32" },
      { name: "commitCount", type: "uint32" },
      { name: "revealCount", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "proposalId", type: "uint256" },
      { name: "oneTimeSalt", type: "bytes32" },
    ],
    name: "revealSalt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    name: "revealedSalts",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
